Start numpy


In [13]:
import numpy as np      #for fast calculations and to work with arrays and matrices

In [14]:
#array means list of numbers  and matrix means list of list 
#array has various functions for calulations and operations but list has only few functions and operations
array = np.array([1,2,3,4,5])
print(array,end='\n\n')

list = [[1,2,3],[4,5,6]] #cant use transpose on list but can use on array
list_array = np.array(list)
print(list_array.T,end='\n\n') 

array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2.T,end='\n\n')

array_3 = np.array([[1,2,3],[4,5,6]])
print(array_3.T)            # .T (transpose) rows=columns and columns=rows (2,3) (2=rows,3=columns) (3,2) (3=rows,2=columns)


[1 2 3 4 5]

[[1 4]
 [2 5]
 [3 6]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4]
 [2 5]
 [3 6]]


In [15]:
import time
start = time.time()         #start time counter
list1 = [i for i in range (1000000)]        #in list we have to use for loop to perform operations on each element 

start = time.time()
array1 = np.array(1000000)    #in array we can perform operations on whole array at once without using for loop and it is faster than list
print('array time:',time.time()-start,end='\n\n')

array time: 9.72747802734375e-05



In [16]:
matrix = np.zeros((2,3,4)) # 2=number of matrices/layers, 3=number of rows, 4=number of columns
print(matrix,end='\n\n')

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



In [17]:
matrix = np.ones((2,3))

print(matrix,end='\n\n')

print(matrix.dtype,end='\n\n')      #find data type of matrix

print(matrix.astype(int),end='\n\n')    #change data type of matrix to int

print((matrix.astype(int).dtype),end='\n\n')


[[1. 1. 1.]
 [1. 1. 1.]]

float64

[[1 1 1]
 [1 1 1]]

int64



In [18]:
matrix = np.full((2,3),7)   #full means all elements of matrix will be filled with the same value (7 in this case)
print(matrix)

[[7 7 7]
 [7 7 7]]


In [19]:
new = np.random.random((2,3))  #random means all elements of matrix will be filled with random values between 0 and 1 and shape of matrix is (2,3)
print(new,end='\n\n')
print(new.shape,end='\n\n')

new1 = np.random.rand(100)
print(new1,end='\n\n')



[[0.53590322 0.67227434 0.30745263]
 [0.89629139 0.31932573 0.71210059]]

(2, 3)

[0.17905017 0.60440452 0.55095222 0.24232656 0.8882482  0.97108554
 0.2219991  0.92744156 0.95888375 0.2669594  0.50696062 0.46165915
 0.87965091 0.2639744  0.73181684 0.41313485 0.68476757 0.68662259
 0.08958903 0.33552742 0.45323184 0.11014396 0.5642266  0.05196921
 0.84480894 0.31875774 0.15241102 0.29808715 0.86736044 0.59616004
 0.67309933 0.40626099 0.91218252 0.39488023 0.72429347 0.42744673
 0.11594121 0.42263966 0.58242607 0.40797008 0.8450688  0.29770499
 0.65508836 0.31913318 0.60072327 0.19843257 0.62991578 0.54327688
 0.72289648 0.82243432 0.34656983 0.42899715 0.00482043 0.48555702
 0.03851526 0.31088783 0.45272248 0.74372557 0.8055339  0.25943655
 0.01924219 0.53693806 0.17845214 0.02379996 0.90962337 0.31343311
 0.93188847 0.45048393 0.15530207 0.34979093 0.73931865 0.30919272
 0.74416814 0.87062076 0.97834973 0.55313592 0.79097429 0.16825314
 0.34438327 0.6215741  0.25981142 0.92039935 0.

In [20]:
arr = np.arange(21,1,-1)
print(arr)

[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [21]:
vector = np.array([1,2,3]) #vector is 1D array and it has only one row or one column but not both
print("vector:\n",vector,end='\n\n')

matrix = np.array([[1,2,3],[4,5,6],[6,7,8]]) #matrix is 2D array and it has rows and columns
print("matrix:\n",matrix)

tensor = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #tensor is 3D array and it has layers, rows and columns (2,3,2) (2=number of layers, 3=number of rows, 2=number of columns)
print("tensor:\n",tensor)

vector:
 [1 2 3]

matrix:
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
array = np.array ([[1,2,3],[4,5,6],[7,8,'shreeram']]) #when we have different data types in array then it will convert all elements to the same data type (in this case it will convert all elements to string)
print(array.itemsize)

84


In [23]:
array = np.array([1,2,3,4,5,6,7,8])
print("data type:",array,array.dtype)
array_1 = array.astype(float)
print("change data type:",array_1,array_1.dtype)
print("shape:",array.shape)
print("size:",array.size)
print("reshape:\n",array.reshape(2,4))
print("dimensions:",array.ndim)
print("transpose:",array.T)
print("type:",type(array))
print("faltten:",array.flatten())
print("ravel:",array.ravel())
print("squeeze:",array.squeeze())
print("item size:",array.itemsize)


data type: [1 2 3 4 5 6 7 8] int64
change data type: [1. 2. 3. 4. 5. 6. 7. 8.] float64
shape: (8,)
size: 8
reshape:
 [[1 2 3 4]
 [5 6 7 8]]
dimensions: 1
transpose: [1 2 3 4 5 6 7 8]
type: <class 'numpy.ndarray'>
faltten: [1 2 3 4 5 6 7 8]
ravel: [1 2 3 4 5 6 7 8]
squeeze: [1 2 3 4 5 6 7 8]
item size: 8


# My practice 

In [43]:
arr = np.array([1,2,3,4,5])
print("arr:\n", arr)
print("dimension:", arr.ndim, end="\n\n")

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:\n", matrix)
print("dimension:", matrix.ndim, end="\n\n")

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor:\n", tensor)
print("dimension:", tensor.ndim, end="\n\n")

arr:
 [1 2 3 4 5]
dimension: 1

matrix:
 [[1 2 3]
 [4 5 6]]
dimension: 2

tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension: 3



In [44]:
num = np.random.random((2,3,4))
print("num:\n", num)
print("dimension:", num.ndim, end="\n\n")

num:
 [[[0.97324752 0.84897689 0.38932964 0.0460164 ]
  [0.72980612 0.24294391 0.19937666 0.00959499]
  [0.607097   0.45870651 0.98897367 0.85884542]]

 [[0.09096794 0.62549205 0.36897703 0.77045765]
  [0.71507873 0.19390581 0.679244   0.43707796]
  [0.94524759 0.46448635 0.78511573 0.79200954]]]
dimension: 3

